sudo: required
services:
   - docker
before_install:
   - docker build -t pericherla/react-test -f ./client/Dockerfile.dev ./client
script:
   - docker run -e CI=true pericherla/react-test npm test
after_success:
   - docker build -t pericherla/multi-client ./client
   - docker build -t pericherla/multi-nginx  ./nginx
   - docker build -t pericherla/multi-server ./server
   - docker build -t pericherla/multi-worker ./worker

   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

   - docker push pericherla/multi-client
   - docker push pericherla/multi-nginx
   - docker push pericherla/multi-server
   - docker push pericherla/multi-worker